<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/photo.css'); ?>
<?php
// set title
$this->headTitle($this->translate('Photo'));
$album = $photo->getAlbum();
$this->headTitle($album->getName());
$currentAlbum = $album;
while(!is_null($currentAlbum->getParent())) {
    $this->headTitle($currentAlbum->getParent()->getName());
    $currentAlbum = $currentAlbum->getParent();
}
$this->headTitle($this->translate('Photos'));
?>
<?php
$this->headScript()->prependFile($this->basePath() . '/js/photo.js')
    ->prependFile($this->basePath() . '/js/jquery.autocomplete.js');
$this->scriptUrl()->requireUrl('member/search');
?>
<?php if ($photo != null): ?>
    <section class="section section-breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li>
                    <a href="<?= $this->url('photo') ?>">
                        <?= $this->translate('Photos') ?>
                    </a>
                </li>
                <li>
                    <?php
                    // determine association year
                    $associationYear = \Decision\Model\AssociationYear::fromDate($photo->getAlbum()->getStartDateTime());
                    ?>
                    <a href="<?= $this->url('photo/year', ['year' => $associationYear->getYear()]); ?>">
                        <?= $associationYear->getYearString() ?>
                    </a>
                </li>
                <?php
                // first we need to get all parents
                $crumbs = [];
                $currentAlbum = $photo->getAlbum();
                while(!is_null($currentAlbum->getParent())) {
                    // prepend parent to array
                    array_unshift($crumbs, [
                        'url'  => $this->url('photo/album', ['album_id' => $currentAlbum->getParent()->getId()]),
                        'name' => $currentAlbum->getParent()->getName()
                    ]);
                    $currentAlbum = $currentAlbum->getParent();
                }
                // then we print them
                foreach($crumbs as $crumb): ?>
                    <li>
                        <a href="<?= $crumb['url'] ?>">
                            <?= $this->escapeHtml($crumb['name']) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
                <li>
                    <a href="<?= $this->url('photo/album', ['album_id' => $photo->getAlbum()->getId()]); ?>">
                        <?= $photo->getAlbum()->getName(); ?>
                    </a>
                </li>
                <li class="active">
                    <?= $this->translate('Photo') ?>
                </li>
            </ol>
        </div>
    </section>
    <div class="container">
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a href="<?= $this->url('photo/album', ['album_id' => $photo->getAlbum()->getId()]); ?>">
                        <span aria-hidden="true">&larr;</span>
                        <?= $this->translate('Return to album') ?>
                    </a>
                </li>
            </ul>
        </nav>
        <div class="row">
            <div class="col-lg-9">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <a href="<?= is_null($next) ? '#' : $this->url('photo/photo', ['photo_id' => $next->getId()]); ?>">
                                <img style="width:100%" src="<?= $this->fileUrl($photo->getLargeThumbPath()) ?>" alt=""/>
                                <?php foreach($photo->getFaces() as $face): ?>
                                    <div class="face" style="width:<?= $face->getWidth()*1.5 ?>px; height: <?= $face->getHeight()*1.5 ?>px; top:<?= $face->getY() - 0.25* $face->getHeight(); ?>px; left:<?= $face->getX()  - 0.25 * $face->getWidth();?>px;">

                                    </div>

                                <?php endforeach; ?>
                            </a>
                            <?php if(!is_null($photo->getWeeklyPhoto())): ?>
                                <div class="carousel-caption">
                                    <span class="glyphicon glyphicon-certificate" aria-hidden="true"></span>
                                    <?= $this->translate('Photo of the week') ?>
                                    <?= $photo->getWeeklyPhoto()->getWeek()->format('d-m-Y') ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php if (!is_null($previous)): ?>
                        <a id="previous" class="left carousel-control"
                           href="<?= $this->url('photo/photo', ['photo_id' => $previous->getId()]); ?>" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only"><?= $this->translate('Previous') ?></span>
                        </a>
                        <?php
                    endif;
                    if (!is_null($next)): ?>
                        <a id="next" class="right carousel-control"
                           href="<?= $this->url('photo/photo', ['photo_id' => $next->getId()]); ?>" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only"><?= $this->translate('Next') ?></span>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col-lg-3">
                <?= $this->partial('partial/metadata.phtml', ['photo' => $photo]) ?>
                <?php if($this->acl('photo_acl')->isAllowed('photo', 'download')): ?>
                    <a class="btn btn-default" href="<?= $this->url('photo/photo_download',
                        ['photo_id' => $photo->getId()]); ?>">
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                        <?= $this->translate('Full resolution'); ?>
                    </a>
                <?php endif; ?>
                <?= $this->partial('partial/tags.phtml', ['photo' => $photo]) ?>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            Photo.initTagging();
        });
    </script>
<?php endif; ?>
